GET http://localhost:8000/customers/2001
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjdXN0b21lcl9pZCI6IjIwMDEiLCJhY2NvdW50cyI6WyI5NTQ3MiIsIjk1NDczIl0sInVzZXJuYW1lIjoiMjAwMSIsInJvbGUiOiJ1c2VyIiwiZXhwIjoxNzQxNzcyMTkwfQ.PxWuu1irE-xL9Z7bMGtWvNN6IqI99DuYynOfkaK-Kbc


###
GET http://localhost:8000/customers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjdXN0b21lcl9pZCI6IiIsImFjY291bnRzIjpudWxsLCJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzQxNzc1ODIxfQ.76mvPLL4XVlNvMik7g1AD2GfWrJsdPfaCy0gisVLRFA
